// File generated by Antigravity (Assistant)
// PLEASE RUN logic: `flutterfire configure` to generate the correct version of this file.
// Or manually replace the values below.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Add other platforms if needed
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqODCvfjwDTMG99gJicaC-QfUO5-d65R8',
    appId: '1:872595389134:web:fc324a62557c212db62e9f',
    messagingSenderId: '872595389134',
    projectId: 'motodo-app',
    authDomain: 'motodo-app.firebaseapp.com',
    storageBucket: 'motodo-app.firebasestorage.app',
  );

}